### ISSUE TITLE
Which version to use? userstyles or github?

### ISSUE THREAD

**Issue by vurtomatic** [vednoc/dark-whatsapp#116]
Hi, thank you for maintaining this theme.

I'm confused as to which version to use. I just updated to v1.7.1 (0.20200116224810) from userstyles which came with a message saying to switch to v2 as v1 is no longer supported.

But on github, I'm seeing:

`USo is still the largest repository for themes despite all the issues. Don’t use this version unless you absolutely have to.`

**Comment by vednoc** [comment]
Hi, glad to hear that!

`wa.user.styl` is the userstyle you should install; every install badge in the repository and the wiki points to it.

`wa.user.css` is a non-customizable version that should be used if you can't use Stylus for whatever reason. Further, it will replace the v2 9n USo when I get around it, and so that users have the time to try out the v2.

`WhatsApp.user.css` is the v2 that's going away. It's there only for

**Comment by vurtomatic** [comment]
Hi @vednoc I had a look at the files you mentioned, and I was wondering if there's an easy way to convert the CSS to JS or if you can share a JS version like the option on userstyles.org's [Install style as userscript](https://userstyles.org/styles/userjs/142096/dark-whatsapp-theme-by-mew.user.js).

I'm using an app called [Hamsket](https://github.com/TheGoddessInari/hamsket), basically a container for different chat services. In the past I've always used the JS, this time I tried injecting your CSS but the app doesn't seem to take it. (JS version from userstyles.org still works.)

**Comment by vednoc** [comment]
JavaScript version is kind of unlikely to happen unless there are people that would use it.

I'll have a look at injecting the CSS when I get back home. The ideal way would be to fetch the raw content of the `wa.user.css` file, strip the metadata and `@-moz-...` property then inject it into the DOM.
