### ISSUE TITLE
Blurred contacts/groups not working

### ISSUE THREAD

**Issue by killmaster** [vednoc/dark-whatsapp#118]
- **Browser**: Firefox 72.0.2
- **Dark-WhatsApp version**: Lite v2.2.1
- **Additional context**: Stopped working since last update. Tried installing again but problem persists.
- **Screenshot**: (Didn't attach because it's just an unblurred contacts list.)

**Comment by vednoc** [comment]
It's disabled by default in the Lite version, so you'll have to install non-lite version by clicking on install badge in the readme (or on the wiki) in order to customize it, then head over to [configuration wiki][0] to see how to enable it.

Did you install it from USo? That's my assumption because a couple of days ago I updated the v2 there, so in the next update I'll have `USo` instead of `Lite` or something like that. :sweat_smile: 

[0]: https://github.com/vednoc/dark-whatsapp/wiki/Configuration#blurred-contactsgroups

**Comment by killmaster** [comment]
I installed it from [here](https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew) on Stylus.

Just installed using [this](https://raw.githubusercontent.com/vednoc/dark-whatsapp/master/wa.user.styl) and changed the settings in Stylus directly.

Everything is working fine now.

Thank you.

**Comment by vednoc** [comment]
> I installed it from here on Stylus.

Thank you for confirming this!


> Everything is working fine now.

Hope you have fun customizing it to your liking. :smiley:

**Comment by xclexcle** [comment]
hi Vednoc, Im experiencing similar issue as well. Im not familiar with alll this coding and stuff but currently using your theme with chrome and unable to use the blurred contacts/group function. Please advise.

Thank you
