### ISSUE TITLE
"No stickers" error text unreadable

### ISSUE THREAD

**Issue by qlcvea** [vednoc/dark-whatsapp#129]
- **Browser**: Firefox Nightly 76.0a1 (2020-03-24), Chrome 80.0.3987.149, Firefox 69.0.3
- **Dark-WhatsApp version**: 2.3.0
- **Additional context**: The error text "You don't have any stickers yet. Download sticker packs on your phone to get started." in a ```<p class="_2Hze1">``` tag is barely readable.
- **Screenshot**: ![Capture](https://user-images.githubusercontent.com/4389687/77558586-645d5780-6ebb-11ea-9221-2acdfac95a04.PNG)

**Comment by vednoc** [comment]
I can't test this without removing stickers, but here is the [link][0] if you'd like to do so, just click on reinstall button and you're all set.

[0]: https://github.com/vednoc/dark-whatsapp/raw/develop/wa.user.styl

**Comment by qlcvea** [comment]
I don't know if it's supposed to be translucent, but at least it's readable now.
![Capture](https://user-images.githubusercontent.com/4389687/77565892-2bc27b80-6ec5-11ea-9fa2-cc5f14b3b139.PNG)

**Comment by vednoc** [comment]
It should look like the example below. Unfortunately I don't know what the selector they're using, and we're adding the transparent background to elements in that area so that's probably why it looks like that. :sweat_smile: 

![image](https://user-images.githubusercontent.com/18245694/77568079-611c9880-6ec8-11ea-9e83-05e4658a078a.png)
