### ISSUE TITLE
Broken after latest update (WhatsApp Version 0.4.2080)

### ISSUE THREAD

**Issue by tinyCoder32** [vednoc/dark-whatsapp#130]
Hi, please take a look at the broken stuff after the last update yesterday.

Latest Chrome.
Latest DarkWhatsApp.

![image](https://user-images.githubusercontent.com/17817239/77701322-0ddd3f80-6fc7-11ea-9894-f386ea1fe131.png)

Thanks.

**Comment by snoopdoge93** [comment]
i just joined github to report a bug, i hope yours is as mine, is white background in launch screen and settings?

**Comment by tinyCoder32** [comment]
I attached a screenshot.

**Comment by snoopdoge93** [comment]
oh yes! i just joined github to report this same bug, thank you

**Comment by snoopdoge93** [comment]
although mine is different, the settings and launch screen is white

**Comment by vednoc** [comment]
The update is quite big so it'll take a while for me to fix it, especially because it's already quite late in my place. I'll try to push an update before heading off for the night.

**Comment by vednoc** [comment]
*4 hours later* :grimacing:

Hotfix update is out! Feel free to open new issues with bugs that you happen to find; I've tried to fix things that are used most of the time and intentionally left out minor things.

Another update might happen tomorrow night because it's going to be quite a busy day for me.
