### ISSUE TITLE
Emoji backgrounds are white

### ISSUE THREAD

**Issue by TaherSH** [vednoc/dark-whatsapp#137]
Browser: Chrome
Dark-WhatsApp version: v2.3.2 (March 27th)
Additional context: The background right behind the emojis are white in the circle, not the entire background.
Screenshot:
![image](https://user-images.githubusercontent.com/28763752/77792166-410ee580-703e-11ea-87e8-8a172812bba1.png)

**Comment by vednoc** [comment]
More info in [vednoc/wae repository][0], feel free to contribute.

The circle clip-path is intentional so that we can minimize the white background for some emojis. 

[0]: https://github.com/vednoc/wae

**Comment by vednoc** [comment]
I'm getting a vague image error when using the tool to convert images that I don't seem to be able to fix or work around. Leaving the emojis as-is for now. Contributions are welcome!

**Comment by vednoc** [comment]
The fix is active in the develop branch; feel free to test it by (re)installing from [this link][0].

Let us know if there are issues related to iOS emojis and/or loading speed — the new images are larger in size so the initial load might not be as fast as before when using a slow connection.

[0]: https://github.com/vednoc/dark-whatsapp/raw/develop/wa.user.styl

**Comment by TaherSH** [comment]
This updated dev version above works! Thank you!

**Comment by EduardoHerreraM** [comment]
Hello. Just updated to 2.3.4, in Firefox, still broken. 
![imagen](https://user-images.githubusercontent.com/45237246/77859996-de1f7900-720c-11ea-9ffb-e1dad7692a08.png)

**Comment by TaherSH** [comment]
The update is still only on the developer version/preview that was posted above, I believe it'll go live on the next update.

**Comment by vednoc** [comment]
I'll reopen this issue and let the GitHub close it automatically once the `develop` branch is merged.

@EduardoHerreraM You have to reinstall it from the link mentioned [here][0], and the emoji images will be active by default because I did a hard-reset for that setting. 


[0]: https://github.com/vednoc/dark-whatsapp/issues/137#issuecomment-605663010
