### ISSUE TITLE
Chat background is broken

### ISSUE THREAD

**Issue by Licanueto** [vednoc/dark-whatsapp#149]
No setting seems to have any effect on that background whatsoever.
Disabling custom image for chat, enabling or disabling the chat background image, changing its opacity, changing the values for the colours, none had any visible effect. 
All other settings work perfectly fine.

- **Browser**: Google Chrome 83.0.4103.14
- **WhatsApp version**: 2.2013.7
- **Dark-WhatsApp version**: 2.3.6
- **Additional context**: OS based on Ubuntu 18.04
- **Screenshot**: ![whatsapp dark broken background blured](https://user-images.githubusercontent.com/17929165/79791256-63391200-8323-11ea-8a1b-9afd498fefe2.jpg)

**Comment by vednoc** [comment]
You probably have the chat background set to one of the gray colors in WhatsApp's settings. We don't have code that would prevent you from using any of the available colors, but the theme works best if you use the default white one.

Navigate to _Settings_ then to _Chat background_ and select the very first color, the one that gives you a background image. I suppose that should fix it since I'm unable to reproduce this issue any other way.

**Comment by Licanueto** [comment]
Yep, that was it! I'll close the issue.
Awesome work, best one I've seen so (and by) far. 
BTW, is there a way to lower de delay there is when hovering over blurred images in the chat?
This doesn't happen when hovering over blurred contacts.

**Comment by vednoc** [comment]
>  BTW, is there a way to lower de delay there is when hovering over blurred images in the chat?

There will be an option in the next update to adjust the in/out hover delay for chat area; contacts area will remain untouched. :smiley:
