### ISSUE TITLE
Text suddenly went black

### ISSUE THREAD

**Issue by aleczk** [vednoc/dark-whatsapp#168]
Ops, I didn't check the 'solutioned' tab before making this post, please delete it. I tried updating directly in the manage styles tab and it didn't work (said it was already updated) but when I went to the stylus store it showed up a new update.

Sorry for the incovenience and thanks for work on the Style, it's my favorite.

**Comment by vednoc** [comment]
Hey @aleczk, no need to worry about making a duplicate issue. What's more, thanks for opening it!

If by "Stylus store" you mean inline search in the Stylus popup, I highly suggest that you [install][0] from GitHub since userstyles.org is having a hard time lately. I also noticed some issues when testing the version I upload there just to be sure that nothing went wrong on their end.

> thanks for work on the Style, it's my favorite.

Glad you like it! 🎉 

[0]: https://github.com/vednoc/dark-whatsapp/wiki/Installation
