### ISSUE TITLE
message count indicator and flashing circle in RTL

### ISSUE THREAD

**Issue by Just-Hussain** [vednoc/dark-whatsapp#175]
- **Browser**: Chrome
- **WhatsApp Web version**: 2.2033.7
- **Dark-WhatsApp version**: USo-Lite 3.0.0-rc.5
- **Additional context**: in RTL
- **Screenshot**:
![dwa-issue](https://user-images.githubusercontent.com/46459187/90416288-f2c8b480-e0ba-11ea-80ef-de37c3e25fba.jpeg)

As seen, the circle is offset and the count does not show.

**Comment by vednoc** [comment]
I had a look at it and this will be resolved tomorrow since I don't have enough time right now. Here's a preview of what it's going to look like, although I might have to adjust positions a tiny bit more:

![image](https://user-images.githubusercontent.com/18245694/90435700-a9369480-e0cf-11ea-9cac-2f018c7071a6.png)

Thank you for bringing this to my attention!
