### ISSUE TITLE
Current differences between v1 & v2

### ISSUE THREAD

**Issue by E-RELevant** [vednoc/dark-whatsapp#66]
While the new version poses more customization options (a welcome move), there are some changes that feel weird to me. I am aware that the second version is in the midst of construction so it may change, but if that is not the case - it is important for me to call your attention.

**v1** is much closer to the original whatsapp view:
1. has a clear difference between the left side of the contact chats and the chat itself with the selected contact (Darker & Dark).
2. Less colors, but color uniformity of embossing like the "Get notified" banner & the scroll-downs.
3. No circular corners for emojis menu.

![image](https://user-images.githubusercontent.com/20738487/69419419-18d84880-0d25-11ea-8409-5f068e3b01ff.png)

While **v2** is lovely, it seems kind of 'broken' with this lack of uniformity.
![image](https://user-images.githubusercontent.com/20738487/69419619-78ceef00-0d25-11ea-9f00-93a998901f3a.png)

**Comment by vednoc** [comment]
There are certain design decisions I had to take while rewriting everything.

> has a clear difference between the left side of the contact chats and the chat itself with the selected contact (Darker & Dark).

Due to the color-palette I'm using, it's troublesome to make it look good all around. I could add an option to make the left side and chat header/footer darker.

> Less colors, but color uniformity of embossing like the "Get notified" banner & the scroll-downs.

Alerts won't change because the default ones tend to be far too distracting. Scrollbars will be fixed in Chrome, I've been using Firefox during the development.

> No circular corners for emojis menu.

Was fixed in 3274bad31a0c30bfeff36e466760d2dad6ec26be.
